name: The Definitive Guide to Ruby's C API
highlighter: pygments
baseurl: /emberb
markdown: kramdown
permalink: /:categories/:title/
gems: ['jekyll-less']
kramdown:
  parse_block_html: true
rbversion: 2.4
